### ISSUE TITLE
add a default config for coderabbitai

### ISSUE THREAD

**Issue by reactive-firewall** [reactive-firewall/ymmv#3]
@coderabbitai please help me configure a `.coderabbit.yaml` from scratch.

**Comment by reactive-firewall** [comment]
@coderabbitai please help me configure a `.coderabbit.yaml` from scratch.

**Comment by reactive-firewall** [comment]
🙈 Why would we exclude tests and docs ❓ Let me draft an improved draft.

**Comment by reactive-firewall** [comment]
@coderabbitai, Let's use the following config to start with:

```yaml
# .coderabbit.yaml
version: 2
language: en
review:
  enabled: true
  instructions: |
    # Code Review Instructions

    - Ensure the code follows best practices and coding standards.
    - Check for security vulnerabilities and potential issues.
    - Ensure the code follows the DRY and AHA principles.
    - Ensure the code follows the SOLID principles.

    # Documentation Review Instructions
    - Verify that documentation and comments are clear and comprehensive.
    - Verify that documentation and comments are free of spelling mistakes.
    - Verify that technical documentation includes a "References" section at the end of documentation, using the same format as actual RFCs, with both "Normative References" and "Informative References".

    # Misc.
    - Ensure that testcode is automated and comprehensive.
    - Confirm that the code meets the project's requirements and objectives.

path_filters:
  include:
    - '**/*.py'
    - '**/*.js'
    - '**/*.sh'
    - '**/*.bash'
    - '**/*.yml'
    - '**/*.md'
    - '.*rc'
    - '.*.conf'
    - '.*.cfg'
    - '.*.yml'
    - '.*.yaml'
    - '.*.json'
    - 'README.md'
    - 'LICENSE.md'
    - 'MAKEFILE'
    - 'tests/check_*'
    - 'tests/test_*'
  exclude:
    - '*.xc*/**'

```

1. Search for any relevant learnings you have and list them in a table.

2. Explore how we can improve this config?

**Comment by reactive-firewall** [comment]
@coderabbitai I like most of your ideas, here's the updated version:

```yaml
# .coderabbit.yaml
version: 2
language: en
review:
  enabled: true
  instructions: |
    # Code Review Instructions

    - Ensure the code follows best practices and coding standards.
    - For **Python** code, follow [PEP 20](https://www.python.org/dev/peps/pep-0020/) and [CEP-8](https://gist.github.com/reactive-firewall/b7ee98df9e636a51806e62ef9c4ab161) standards.
    - For **BASH** and **Shellscript** code, follow [Pure BASH Bible](https://github.com/dylanaraps/pure-bash-bible) and [CEP-5](https://gist.github.com/reactive-firewall/3d2bd3cf37f87974df6f7bee31a05a89) standards.

    - Check all bash files start with an [exstensive disclaimer](https://gist.github.com/reactive-firewall/866b42d175ae3ebefcb2a5878b30ea17).
    - Check for security vulnerabilities and potential issues.
    - Ensure the code follows the DRY AHA and SOLID principles.

    # Documentation Review Instructions
    - Verify that documentation and comments are clear and comprehensive.
    - Verify that documentation and comments are free of spelling mistakes.
    - Verify that technical documentation includes a "References" section at the end of documentation, using the same format as actual RFCs, with both "Normative References" and "Informative References".

    # Test Code Review Instructions
    - Ensure that test code is automated, comprehensive, and follows testing best practices.
    - Verify that all critical functionality is covered by tests.

    # Misc.
    - Confirm that the code meets the project's requirements and objectives.
    - Confirm that copyright years are up-to date whenever a file is changed.

path_filters:
  include:
    - '**/*.{py,js,sh,bash,yml,yaml,json,md}'
    - '.*{rc,conf,cfg,yml,yaml,json}'
    - 'README.md'
    - 'LICENSE.md'
    - 'MAKEFILE'
    - 'tests/check_*'
    - 'tests/test_*'
    - 'docs/**'
  exclude:
    - '*.xc*/**'
    - 'node_modules/**'
    - 'dist/**'
    - 'build/**'

```

Now what sort of configuration improvements can we add for [languagetool](https://docs.coderabbit.ai/tools/languagetool)? How else can we improve this config?

**Comment by reactive-firewall** [comment]
@coderabbitai, 1. let's explore `languagetool`'s `enabled_rules` and `disabled_rules`
2. what about the tool `ruff`?

**Comment by reactive-firewall** [comment]
@coderabbitai, help me configure ruff to be more like flake8 and configure things like "dummy-variable-rgx" so I can fine tune the style.

**Comment by reactive-firewall** [comment]
@coderabbitai, Now we're getting somewhere; here is the current version:

```yaml
# .coderabbit.yaml
version: 2
language: en
review:
  enabled: true
  instructions: |
    # Code Review Instructions

    - Ensure the code follows best practices and coding standards.
    - For **Python** code, follow [PEP 20](https://www.python.org/dev/peps/pep-0020/) and [CEP-8](https://gist.github.com/reactive-firewall/b7ee98df9e636a51806e62ef9c4ab161) standards.
    - For **BASH** and **Shellscript** code, follow [Pure BASH Bible](https://github.com/dylanaraps/pure-bash-bible) and [CEP-5](https://gist.github.com/reactive-firewall/3d2bd3cf37f87974df6f7bee31a05a89) standards.
    - Check all bash files start with an [extensive disclaimer](https://gist.github.com/reactive-firewall/866b42d175ae3ebefcb2a5878b30ea17).
    - Check for security vulnerabilities and potential issues.
    - Ensure the code follows the **DRY, AHA, and SOLID** principles.

    # Documentation Review Instructions
    - Verify that documentation and comments are clear and comprehensive.
    - Verify that documentation and comments are free of spelling mistakes.
    - Verify that technical documentation includes a "References" section at the end of documentation, using the same format as actual RFCs, with both "Normative References" and "Informative References".

    # Test Code Review Instructions
    - Ensure that test code is automated, comprehensive, and follows testing best practices.
    - Verify that all critical functionality is covered by tests.

    # Misc.
    - Confirm that the code meets the project's requirements and objectives.
    - Confirm that copyright years are up-to date whenever a file is changed.

linters:
  languagetool:
    enabled: true
    language: en-US
    configuration:
      level: picky
      mother_tongue: en
      dictionary:
        - 'reactive-firewall'
        - 'CEP-8'
        - 'CEP-5'
        - 'Shellscript'
        - 'bash'
      disabled_rules:
        - EN_QUOTES
        - CONSECUTIVE_SPACES
      enabled_rules:
        - STYLE
        - EN_CONTRACTION_SPELLING
        - EN_WORD_COHERENCY
        - IT_IS_OBVIOUS
        - TWELFTH_OF_NEVER
        - OXFORD_SPELLING
        - PASSIVE_VOICE
  flake8:
    enabled: true
  shellcheck:
    enabled: true
  ruff:
    enabled: true
    configuration:
      extend_select:
        - E  # Pycodestyle errors (style issues)
        - F  # PyFlakes codes (logical errors)
        - W  # Pycodestyle warnings
        - N  # PEP 8 naming conventions
      ignore:
        - W191
        - W391
        - E117
        - D208
      line_length: 100
      dummy_variable_rgx: '^(_.*|junk|extra)$'  # Variables starting with '_' or named 'junk' or 'extras', are considered dummy variables
      external:
        flake8-blind-except: {}
        flake8-docstrings: {}
        flake8-comprehensions: {}
        flake8-debugger: {}
        flake8-comprehensions: {}
        flake8-eradicate: {}
        # Include other Flake8 plugins as needed
  markdownlint:
    enabled: true
  yamllint:
    enabled: true
  jsonlint:
    enabled: true

path_filters:
  include:
    - '**/*.{py,js,sh,md,txt,yml,bash,yaml,json}'
    - '.*{rc,conf,cfg,yml,yaml,json}'
    - 'README.md'
    - 'LICENSE.md'
    - 'MAKEFILE'
    - 'tests/check_*'
    - 'tests/test_*'
    - 'docs/**'
  exclude:
    - '*.xc*/**'
    - 'node_modules/**'
    - 'dist/**'
    - 'build/**'

```

* what about flake8, yamllint, markdownlint, and ShellCheck configuration files? How can we specify their locations?

* can we include the `ast-grep` patterns from [the scripts of this comment](https://github.com/reactive-firewall/multicast/issues/79#issuecomment-2392827329)?

* what else can we improve further?
